# Test 환경 설정
spring:
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password: 
    driver-class-name: org.h2.Driver
    hikari:
      maximum-pool-size: 5
      minimum-idle: 1
  
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: false
  
  h2:
    console:
      enabled: true
  
  kafka:
    # 테스트에서는 Kafka 비활성화
    enabled: false

logging:
  level:
    com.consumer.cconsumer: INFO
    org.springframework.kafka: WARN
    org.hibernate: WARN