# Development 환경 설정
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/consumer_db
    username: root
    password: password
    hikari:
      maximum-pool-size: 10
      minimum-idle: 3
      leak-detection-threshold: 30000
  
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        jdbc:
          batch_size: 10
  
  kafka:
    consumer:
      bootstrap-servers: localhost:9092
    schema-registry:
      url: http://localhost:8081

logging:
  level:
    com.consumer.cconsumer: DEBUG
    org.springframework.kafka: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE