# Production 환경 설정
spring:
  datasource:
    url: ${DB_URL:jdbc:mysql://localhost:3306/consumer_db}
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:password}
    hikari:
      maximum-pool-size: 50
      minimum-idle: 10
      idle-timeout: 600000
      max-lifetime: 3600000
      connection-timeout: 30000
      leak-detection-threshold: 120000
  
  jpa:
    show-sql: false
    properties:
      hibernate:
        format_sql: false
        jdbc:
          batch_size: 50
          order_inserts: true
          order_updates: true
        connection:
          provider_disables_autocommit: true
        cache:
          use_second_level_cache: false
  
  kafka:
    consumer:
      bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    schema-registry:
      url: ${SCHEMA_REGISTRY_URL:http://localhost:8081}

logging:
  level:
    com.consumer.cconsumer: INFO
    org.springframework.kafka: WARN
    org.hibernate: WARN
    org.springframework.web: WARN
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  
# 운영 환경 보안 설정
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: when-authorized