spring:
  application:
    name: codex-consumer
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:19092}
    consumer:
      group-id: codex-consumer-group
      auto-offset-reset: earliest
      enable-auto-commit: false
    listener:
      ack-mode: manual_immediate
    producer:
      client-id: codex-consumer
  datasource:
    hikari:
      pool-name: codexConsumerPool
      maximum-pool-size: ${CODEX_CONSUMER_HIKARI_MAX_POOL_SIZE:10}
      minimum-idle: ${CODEX_CONSUMER_HIKARI_MIN_IDLE:3}
      connection-timeout: ${CODEX_CONSUMER_HIKARI_CONN_TIMEOUT:30000}
      validation-timeout: ${CODEX_CONSUMER_HIKARI_VALIDATION_TIMEOUT:5000}
  jpa:
    open-in-view: false
    properties:
      hibernate:
        format_sql: true

codex:
  kafka:
    listener:
      concurrency: ${CODEX_KAFKA_LISTENER_CONCURRENCY:1}
      ack-mode: ${CODEX_KAFKA_LISTENER_ACK_MODE:MANUAL_IMMEDIATE}
    retry:
      interval-millis: ${CODEX_KAFKA_RETRY_INTERVAL:1000}
      max-attempts: ${CODEX_KAFKA_RETRY_MAX_ATTEMPTS:2}
    avro:
      specific-reader: ${CODEX_KAFKA_AVRO_SPECIFIC_READER:true}
