CREATE DATABASE IF NOT EXISTS consumer_db;
USE consumer_db;

CREATE TABLE IF NOT EXISTS MYDATA_TERMINATE_USER (
    id BIGINT NOT NULL AUTO_INCREMENT,
    pay_account_id BIGINT NOT NULL,
    terminate_status ENUM('PENDING', 'COMPLETED') NOT NULL DEFAULT 'PENDING',
    reason VARCHAR(255) DEFAULT NULL,
    created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
    PRIMARY KEY (id),
    UNIQUE KEY uq_mydata_pay_account_status (pay_account_id, terminate_status)
);

CREATE TABLE IF NOT EXISTS PAY_TERMINATE_USER (
    id BIGINT NOT NULL AUTO_INCREMENT,
    pay_account_id BIGINT NOT NULL,
    terminate_status ENUM('PENDING', 'COMPLETED') NOT NULL DEFAULT 'PENDING',
    reason VARCHAR(255) DEFAULT NULL,
    created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
    PRIMARY KEY (id),
    UNIQUE KEY uq_pay_pay_account_status (pay_account_id, terminate_status)
);
